spring:
  application:
    name: beans-profile
  datasource:
    url: jdbc:postgresql://${DB_HOST:beans-profile-psql}:${DB_PORT:5432}/${DB_NAME:profile_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: beans-profile-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
jwt:
  secret-key: ${JWT_SECRET_KEY:default-secret-key}
barista:
  registration:
    key: ${BARISTA_REGISTRATION_KEY:default-registration-key}
server:
  port: 8001
